package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.kubernetesExecutor
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            kubernetesExecutor {
                id = "PROJECT_EXT_125"
                connectionId = "PROJECT_EXT_2"
                profileName = "K8s Executor"
                buildsLimit = "2"
                containerParameters = "a=a1,b=b1"
                templateName = "ubuntu-agent"
            }
        }
    }
}
